config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :recipes do
    member do
      put 'like', to: 'recipes#upvote'
      put 'dislike', to: 'recipes#downvote'
    end
    resources :comments, only: %i[create destroy]
  end
  root to: 'recipes#index'
  get '/user/profile' => 'users#show'

  resources :users do
    resources :recipes
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  acts_as_votable
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :directions
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
  validates :name, :description, :image, presence: true
  validates :name, uniqueness: true
  validates :recipe_ingredients, presence: true
  validates :directions, presence: true
  accepts_nested_attributes_for :recipe_ingredients, reject_if: proc { |attr| attr[:quantity].blank? && attr[:ingredient_attributes][:name].blank? }, allow_destroy: true
  accepts_nested_attributes_for :directions, reject_if: proc { |attr| attr[:step].blank? }, allow_destroy: true

  has_attached_file :image, styles: { medium: '400x400#' }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  def self.recently_added_recipes
    Recipe.last(4).reverse
     end

  scope :by_alphabet, -> { order(:name) }

  def next
    if next_recipe = self.class.where('id > ?', id).first
      next_recipe
    else
      Recipe.first
    end
 end
  end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	before_action :set_recipe ,only: [:show,:edit,:update,:destroy]
	
	def index
		@recent_recipes = Recipe.recently_added_recipes
		if params[:user_id]
			@recipes = User.find(params[:user_id]).recipes
		else
			@recipes = Recipe.all.by_alphabet
			respond_to do |format|
				format.html {render :index}
				format.json {render json: @recipes}
			end
		end
	end
	
	def show
		@recipe = Recipe.find(params[:id])
		if current_user
			@comment = current_user.comments.build(recipe: @recipe)
		end
		respond_to do |format|
			format.html {render :show}
			format.json {render json: @recipe}
		end
	end
	
	def new
		if user_signed_in?
			@recipe = Recipe.new
		else 
			redirect_to  new_user_session_path
		end
	end
		
	def create
		@recipe = Recipe.create (recipe_params)
		if @recipe.save
			redirect_to recipe_path(@recipe) , notice: "Successfully created new recipe"
		else
			render 'new'
		end
	end
	
	def edit
	end
	
	def update
		if @recipe.update(recipe_params)
			redirect_to @recipe, notice: "Recipe successfully updated."
		else
			render :edit
		end
	end
	
	def destroy
		@recipe.destroy
		redirect_to @recipe, notice: "Recipe successfully destroyed."
	end
	
	def upvote
		@recipe = Recipe.find(params[:id])
		@recipe.upvote_by current_user
		redirect_back fallback_location: root_path
	end
	
	def downvote
		@recipe = Recipe.find(params[:id])
		@recipe.downvote_by current_user
		redirect_back fallback_location: root_path
	end
	
	private
		
	def set_recipe
		@recipe = Recipe.find(params[:id])
	end
	
	def recipe_params
		params.require(:recipe).permit(
			:name,
			:description,
			:image,
			:user_id,
			directions_attributes: [:id, :step],
			recipe_ingredients_attributes: [
			:id,
			:quantity,
			:recipe_id,
			:ingredient_id,
			ingredient_attributes: [:id, :name]])
	end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_direction_fields.html.erb
<div class="form-inline clearfix"> 
	<div class="nested-fields">
		<%= f.label :step, "Step:" %>
		<%= f.text_field :step, class: 'form-control' %>
		 <%= link_to_remove_association "Remove", f, class: "btn btn-default form-button" %>
	</div>
	</div>

app/views/recipes/_form.html.erb
	<%= form_for @recipe do |f| %>
	
	<% if recipe.errors.any? %>
		<div id="error_explanation">
			<h4><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h4>
				<ul>
					<% recipe.errors.full_messages.each do |message| %>
					<li><%= message %></li>
					<% end %>
				</ul>
			</div>
	<% end %>

	<div class="panel-body">
		<%= f.label :name, "Recipe Name" %>
		<%= f.text_field :name, class: 'form-control'%>

		<%= f.label :description, "Description" %>
		<%= f.text_area :description, class: 'form-control'%> <br>
		<%= f.file_field :image, class: 'form-control'%> <br>
		
		
	<div class="row">
   <div class="col-md-6">
	  <div id="recipe-ingredients">
	   <ol>
	    <h3>Ingredients</h3>
	      <%= f.fields_for(:recipe_ingredients) do |ri| %>
	       <%= render 'recipe_ingredient_fields', f: ri  %>
	      <% end %>
	           <%= link_to_add_association 'Add Ingredient', f, :recipe_ingredients,
               'data-association-insertion-node' => "#recipe-ingredients ol",
                'data-association-insertion-method' => "append",
                :wrap_object => Proc.new {|ri| ri.build_ingredient; ri }, class: "btn btn-default form-button" %>
         </ol>
        </div>
       
       <div class="col-md-6"> 
        <div id="directions">
	        <h3>Directions</h3>
		       <%= f.fields_for(:directions) do |direction| %>
	           <%= render 'direction_fields', f: direction %>
	           <% end %>
	           <%= link_to_add_association 'Add Step', f, :directions,
               'data-association-insertion-node' => "#directions ",
                'data-association-insertion-method' => "append", class: "btn btn-default form-button" %>
             <br />
	           <%= f.hidden_field(:user_id, value: current_user.id) %>
		     </div>
	     </div>
     </div>
   </div>
  </div>
<%= f.submit "Create Recipe", class: "btn btn-primary" %> 
<% end %>
	

app/views/recipes/_latest_recipes.html.erb
 <% @recent_recipes.each do |recipe| %>
    <div class="col-md-3 col-sm-6 hero-feature">
      <div  data-aos="flip-left"
        data-aos-easing="ease-out-cubic"
        data-aos-duration="2000">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= recipe.image if recipe.image.present? %>');">
         <div class="card-description">
					 <h2><%= recipe.name %></h2>
         </div>
        <%= link_to '', recipe_path(recipe), class: "card-link" %>
        </div>
      </div>
  </div>
  <% end %>


app/views/recipes/_recipe_ingredient_fields.html.erb
<div class="form-inline  clearfix">
  <div class=" form-group nested-fields">
	 <%= f.label :quantity, "Quantity" %>
		<%= f.text_field :quantity, class: 'form-control'%>

		<%= f.fields_for(:ingredient) do |ri_ingredient| %>
		<%= ri_ingredient.label :name, "Name" %>
		<%= ri_ingredient.text_field :name, class: 'form-control'%>
	  <% end %>
		<%= link_to_remove_association "Remove", f, class: "btn btn-default form-button" %> 
	</div>
</div>




app/views/recipes/_votes.html.erb
<div class="btn-group pull-left">
  <%= link_to like_recipe_path(@recipe), method: :put, class: "btn btn-default" do %>
    <span class="glyphicon glyphicon-chevron-up"></span>
    Upvote
    <%= @recipe.get_upvotes.size %>
  <% end %>
  <%= link_to dislike_recipe_path(@recipe), method: :put, class: "btn btn-default" do %>
	<span class="glyphicon glyphicon-chevron-down"></span>
    Downvote
    <%= @recipe.get_downvotes.size %>
  <% end %>
</div>

app/views/recipes/edit.html.erb
  <div class="banner home-banner recipe-banner">
  <div class="banner-content">
    <h1>Edit Recipe</h1>
  </div>
</div>
	
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
	
	   <%= render "form", recipe: @recipe %>
	  </div>
   </div>
 </div>
<button type="button" class="btn btn-default">
	<%= link_to 'Back', recipes_path %>
</button>

app/views/recipes/index.html.erb



<div class="banner home-banner">
  <div class="banner-content">
    <h1>SAVORY</h1>
     <p><span id="intro"></span></p>
     <%= link_to "Add Your Own Recipe", new_recipe_path, class: "btn btn-primary btn-lg my-btn"%>
  </div>
</div>
 <h2 class="text-center title">Latest Recipes</h2>
  <%= render "latest_recipes", recipe: @recipe %>
    <br />
 <div class="container">
   <h2 class="text-center title">Our Library of Recipes</h2>
   <div class="row">
    <% @recipes.each do |recipe| %>
    <div class="col-xs-12 col-sm-4">
      <div data-aos="flip-left"
        data-aos-easing="ease-out-cubic"
        data-aos-duration="2000">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= recipe.image if recipe.image.present? %>');">
         <div class="card-description">
            <h2><%= link_to recipe.name, recipe_path(recipe)%></h2>
             <p id="description-<%= recipe.id %>"> <%= truncate(recipe.description, length:25)%></p>
              <a href="#" class="js-more btn btn-default btn-sm" data-id="<%= recipe.id %>">Read more<span class=" glyphicon glyphicon-chevron-right" aria-hidden="true"></span></a>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  </div>
</div>
<script src="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.js"></script>

app/views/recipes/new.html.erb
<div class="banner home-banner recipe-banner">
  <div class="banner-content">
    <h1>Add A New Recipe</h1>
  </div>
</div>
	
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
	
	   <%= render "form", recipe: @recipe %>
	  </div>
   </div>
 </div>
<button type="button" class="btn btn-default">
	<%= link_to 'Back', recipes_path %>
</button>

app/views/recipes/show.html.erb
<div class="banner recipe-banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
	url('<%=  @recipe.image.url %>')">
	<div class="banner-content">
  	<h1><%= @recipe.name %></h1>
	</div>
</div>

	<div class="container">
  	<div class="row">
     <div class="details-recipe">
      <div class="col-md-4">
        	<h4>Description</h4>
        	<p><%= @recipe.description %></p>
        <div class="chefName"><strong>Created by: Chef <%= link_to @recipe.user.username, user_recipes_path(@recipe.user) %></strong></div> 
      </div>
    
      <div class="col-md-4">
        <h4>Ingredients</h4>
         <% @recipe.recipe_ingredients.each do |ri| %>
          <ul>
          	<li class="recipeIngredients"><%= ri.quantity %> of <%= ri.ingredient.name %> </li> 
          </ul>
        <% end %> 
      </div>
      
      <div class="col-md-4">
        <h4>Directions:</h4>
        	<% @recipe.directions.each do |d| %>
          <ul>
         		<li class="recipeSteps"><%= d.step %></li>
          <% end %>
         </ul>
      </div>
    </div>
  </div>
</div>
<br>
	
 	<button type="button" class="btn btn-default">
    <%= link_to 'Back', recipes_path %>
   </button>
	<% if @recipe.user == current_user %>
   <button type="button" class="btn btn-default">
    <%= link_to 'Edit',  edit_recipe_path %>
    </button>
     <button type="button" class="btn btn-default">
    	<%= link_to 'Delete', recipe_path, method: :delete, data:{confirm: "Are you sure?"} %>
     </button>
	<% end %>
	 <%= render "votes", recipe: @recipe %>
 <br />
 

<div class="row">
  <div class="well-white">
    <h2>Comment(s)</h2>
      <hr>
       <div id="submitted-comments">
        <% @recipe.comments.each do |comment| %>
         <blockquote>
         <div class="well-white well-white" id="comment-<%= comment.id %>">
           <strong class="commentUserName"><%= comment.user.username %></strong> commented: <span class="commentContent"><%= comment.body %> </span> <span ><%= link_to '',recipe_comment_path(@recipe, comment), method: :delete,
              data: { confirm: 'Are you sure?' }, class: 'glyphicon glyphicon-trash' %> </span>
         </div>
				</blockquote>
      <% end %>
    </div>
   </div>
  </div>
   <% if current_user %>
      <h4>Add a comment:</h4>
        <%= form_for @comment, url: recipe_comments_path(@recipe, @comment)  do |f| %>
           <p><%= f.text_area :body, class: 'commentBox form-control' %></p>
          <button type="submit" class="btn btn-sm btn-primary">Create Comment</button>
        <% end %>
       <br>
    <% else %>
   <p>Please login in order to add a comment.</p>
  <% end %>
 