config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :recipes do
    member do
      put 'like', to: 'recipes#upvote'
      put 'dislike', to: 'recipes#downvote'
    end
    resources :comments, only: %i[create destroy]
  end
  root to: 'recipes#index'
  get '/user/profile' => 'users#show'

  resources :users do
    resources :recipes
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flash.html.erb
<%if flash[:notice] %>
<div class="alert alert-dismissible alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <p><%=flash[:notice]%></p>
</div>
<%end%>

<%if flash[:alert] %>
    <div class="alert alert-dismissible alert-info">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <p><%= flash[:alert] %></p>
    </div>
<% end %>

<%if flash[:error]%>
    <div class="alert alert-dismissible alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <p><%=flash[:error]%></p>
    </div>
<%end%>

app/views/layouts/_nav.html.erb
 <nav class="navbar navbar-inverse">
     <div class="container-fluid">
       <div class="navbar-header">
         <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>                        
         </button>
        <div id="logo" class="navbar-brand">
         <span>  <%= image_tag "logo.png" %> SAVORY </span>
         
        </div>
		 </div>
         <div class="collapse navbar-collapse" id="myNavbar">
           <% if user_signed_in? %>
		     <ul class="nav navbar-nav navbar-right">
			  <li><%= link_to 'Recipes', recipes_path %></li>
			  <li><%= link_to 'Add a new recipe', new_user_recipe_path(current_user) %></li>
			  
			  <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Account
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
			  <li><%= link_to "My Profile", user_path(current_user), class:'user' %></li>
			  <li><%= link_to ' Edit Account', edit_user_registration_path %></li>
			   </ul>
      </li>
       <li><a href="#"><%= current_user.username.capitalize %></a></li>
			  <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
			</ul>
		 	<% else %>
				<ul class="nav navbar-nav pull-right">
				  <li><%= link_to 'Recipes', recipes_path %></li>
				  <li><%= link_to 'Sign up', new_user_registration_path %></li>
				  <li><%= link_to 'Sign in', new_user_session_path %></li>
			  </ul>
		  <% end %>
		</div>
      </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Savory</title>
     <%= csrf_meta_tags %>
     <meta name="viewport" content="width=device-width, initial-scale=1">
     <link href="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "recipes", 'data-turbolinks-track': 'reload'%>
  </head>

  <body>
    	 <div id="main_content" class="container">
     	 <%= render "layouts/nav" %>
       <%= render "layouts/flash" %>
       <div id="app-container">
    <%= yield %>
    </div>
		</div>
  </body>
</html>